[versions]
# Android
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

androidxActivityCompose = "1.9.3"
agp = "8.7.2"
coreLibraryDesugaring = "2.1.3"

# Kotlin
kotlin = "2.1.0"
kotlinxCoroutines = "1.9.0"
kotlinxSerialization = "1.7.3"
ksp = "2.1.0-1.0.29"

# Compose
composeMultiplatform = "1.7.1"
composeNavigation = "2.8.0-alpha10"

# Shared
ktlintGradlePlugin = "12.1.1"
ktlint = "0.50.0"
detekt = "1.23.6"
detektCompose = "0.0.26"
koin = "4.0.0"
arrow = "2.0.0"
sqldelight = "2.0.2"

# Server
ktor = "2.3.12" # update to 3.x.x when available (check Koin support), check https://github.com/InsertKoinIO/koin/pull/1978
logback = "1.5.7"
postgresql = "42.5.1"
h2-version = "2.2.224"
firebaseAdmin = "9.3.0"
hikari = "6.0.0"

[libraries]
# Android
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
core-library-desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }

# Kotlin
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Compose
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

# Shared
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }

koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }

arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow" }

# shared ktor dependencies
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }

# ktor client specific dependencies
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources" }

# ktor server specific dependencies
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging-jvm" }
ktor-server-default-headers = { group = "io.ktor", name = "ktor-server-default-headers-jvm" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors-jvm" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources-jvm" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth-jvm" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages" }
sqldelight-driver-jdbc = { group = "app.cash.sqldelight", name = "jdbc-driver", version.ref = "sqldelight" }
sqldelight-dialect-postgresql = { group = "app.cash.sqldelight", name = "postgresql-dialect", version.ref = "sqldelight" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }

# ktor server related dependencies
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2-version" }
firebase-admin = { group = "com.google.firebase", name = "firebase-admin", version.ref = "firebaseAdmin" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-formatting-compose = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "detektCompose" }
ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintGradlePlugin" }
kotlin-compose-compiler-gradlePlugin = { group ="org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

# Compose
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

# Shared
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# Plugins defined by this project
notes-multiplatform-application = { id = "notes.multiplatform.application", version = "unspecified" }
notes-android-application = { id = "notes.android.application", version = "unspecified" }
notes-library = { id = "notes.android.library", version = "unspecified" }
notes-multiplatform-application-compose = { id = "notes.multiplatform.application.compose", version = "unspecified" }
notes-library-compose = { id = "notes.android.library.compose", version = "unspecified" }
notes-jvm-library = { id = "notes.jvm.library", version = "unspecified" }
notes-productflavors = { id = "notes.productflavors", version = "unspecified" }
notes-buildtypes = { id = "notes.buildtypes", version = "unspecified" }
notes-versioning = { id = "notes.versioning", version = "unspecified" }
notes-quality = { id = "notes.quality", version = "unspecified" }

[bundles]
arrow = [
    "arrow-core",
    "arrow-coroutines",
]

ktor-client = [
    "ktor-client-core",
    "ktor-auth",
    "ktor-client-encoding",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "ktor-client-resources",
]

ktor-server = [
    "ktor-server-core",
    "ktor-server-content-negotiation",
    "ktor-server-call-logging",
    "ktor-server-default-headers",
    "ktor-server-cors",
    "ktor-server-resources",
    "ktor-server-auth",
    "ktor-server-netty",
    "ktor-server-config-yaml",
    "ktor-serialization-kotlinx-json",
    "ktor-server-status-pages",
]
