name: Distribute release prod APK

on:
  workflow_dispatch:

jobs:
  distribute_release_build:
    runs-on: ubuntu-latest
    env:
      NOTES_STORE_PASSWORD: '${{ secrets.NOTES_STORE_PASSWORD }}'
      NOTES_KEY_PASSWORD: '${{ secrets.NOTES_KEY_PASSWORD }}'

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Assemble
        run: |
          ./gradlew assembleProdRelease --stacktrace

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: app-prod-release.apk
          path: app/build/outputs/apk/prod/release/