name: PR checks

on:
  push:
    branches:
      - master
      - 'release*'
      - develop
  pull_request:
    branches:
      - master
      - 'release*'
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static_analysis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Static Analysis
        run: ./gradlew ktlintCheck detekt --stacktrace

  build_android:
    runs-on: macos-latest
    env:
      NOTES_STORE_PASSWORD: '${{ secrets.NOTES_STORE_PASSWORD }}'
      NOTES_KEY_PASSWORD: '${{ secrets.NOTES_KEY_PASSWORD }}'
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Assemble
        run: ./gradlew assembleProdRelease --stacktrace

  build_server:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Build server
        run: ./gradlew :server:build --stacktrace

  unit_tests:
    runs-on: macos-latest
    env:
      NOTES_STORE_PASSWORD: '${{ secrets.NOTES_STORE_PASSWORD }}'
      NOTES_KEY_PASSWORD: '${{ secrets.NOTES_KEY_PASSWORD }}'
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Unit tests
        run: |
          ./gradlew composeApp:test --stacktrace
          ./gradlew shared:test --stacktrace
          ./gradlew server:test --stacktrace
