name: Tests

on:
  push:
    branches:
      - master
      - 'release*'
      - develop
  pull_request:
    branches:
      - master
      - 'release*'
      - develop

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Static Analysis
        run: |
          ./gradlew ktlintCheck detekt --stacktrace

  build:
    needs: [ static_analysis ]
    runs-on: ubuntu-latest
    env:
      NOTES_STORE_PASSWORD: '${{ secrets.NOTES_STORE_PASSWORD }}'
      NOTES_KEY_PASSWORD: '${{ secrets.NOTES_KEY_PASSWORD }}'
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Assemble
        run: |
          ./gradlew assembleProdRelease --stacktrace

  unit_tests:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      NOTES_STORE_PASSWORD: '${{ secrets.NOTES_STORE_PASSWORD }}'
      NOTES_KEY_PASSWORD: '${{ secrets.NOTES_KEY_PASSWORD }}'
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit tests
        run: |
          ./gradlew app:test --stacktrace
